
----------------------------------------------------
-- PolicyBranchTypes
----------------------------------------------------
INSERT INTO PolicyBranchTypes
	(Type,							Description,							Help,										Title,							EraPrereq,		PurchaseByLevel, AIDelayNoScience)
VALUES
	('POLICY_BRANCH_PROSPERITY',	'TXT_KEY_POLICY_BRANCH_PROSPERITY',		'TXT_KEY_POLICY_BRANCH_PROSPERITY_HELP',	'TXT_KEY_PROSPERITY_TITLE',		'ERA_ATOMIC',	1,				1);

INSERT INTO Policies
	(Type,								Description,								Civilopedia,									Help,											PolicyBranchType,				CultureCost, Level, PortraitIndex, IconAtlas,           IconAtlasAchieved)
VALUES
	('POLICY_POP_ART',					'TXT_KEY_POLICY_POP_ART',					'TXT_KEY_POLICY_POP_ART_PEDIA',					'TXT_KEY_POLICY_POP_ART_HELP',					'POLICY_BRANCH_PROSPERITY',		10,          1,     10,            'POLICY_ATLAS_EXP2', 'POLICY_A_ATLAS_EXP2'),
	('POLICY_REGULATORY_CAPTURE',		'TXT_KEY_POLICY_REGULATORY_CAPTURE',		'TXT_KEY_POLICY_REGULATORY_CAPTURE_PEDIA',		'TXT_KEY_POLICY_REGULATORY_CAPTURE_HELP',		'POLICY_BRANCH_PROSPERITY',		10,          1,     10,            'POLICY_ATLAS_EXP2', 'POLICY_A_ATLAS_EXP2'),
	('POLICY_LOBBYISTS',				'TXT_KEY_POLICY_LOBBYISTS',					'TXT_KEY_POLICY_LOBBYISTS_PEDIA',				'TXT_KEY_POLICY_LOBBYISTS_HELP',				'POLICY_BRANCH_PROSPERITY',		10,          1,     10,            'POLICY_ATLAS_EXP2', 'POLICY_A_ATLAS_EXP2'),
	('POLICY_GOSPEL_OF_WEALTH',			'TXT_KEY_POLICY_GOSPEL_OF_WEALTH',			'TXT_KEY_POLICY_GOSPEL_OF_WEALTH_PEDIA',		'TXT_KEY_POLICY_GOSPEL_OF_WEALTH_HELP',			'POLICY_BRANCH_PROSPERITY',     10,          1,     10,            'POLICY_ATLAS_EXP2', 'POLICY_A_ATLAS_EXP2'),
	('POLICY_INSIDER_TRADING',			'TXT_KEY_POLICY_INSIDER_TRADING',			'TXT_KEY_POLICY_INSIDER_TRADING_PEDIA',			'TXT_KEY_POLICY_INSIDER_TRADING_HELP',			'POLICY_BRANCH_PROSPERITY',     10,          1,     10,            'POLICY_ATLAS_EXP2', 'POLICY_A_ATLAS_EXP2'),
	('POLICY_TOO_BIG_TO_FAIL',			'TXT_KEY_POLICY_TOO_BIG_TO_FAIL',			'TXT_KEY_POLICY_TOO_BIG_TO_FAIL_PEDIA',			'TXT_KEY_POLICY_TOO_BIG_TO_FAIL_HELP',			'POLICY_BRANCH_PROSPERITY',     10,          1,     10,            'POLICY_ATLAS_EXP2', 'POLICY_A_ATLAS_EXP2'),
	('POLICY_SOFT_POWER',				'TXT_KEY_POLICY_SOFT_POWER',				'TXT_KEY_POLICY_SOFT_POWER_PEDIA',				'TXT_KEY_POLICY_SOFT_POWER_HELP',				'POLICY_BRANCH_PROSPERITY',     10,          1,     10,            'POLICY_ATLAS_EXP2', 'POLICY_A_ATLAS_EXP2'),
	('POLICY_DIPLOMATIC_IMMUNITY',		'TXT_KEY_POLICY_DIPLOMATIC_IMMUNITY',		'TXT_KEY_POLICY_DIPLOMATIC_IMMUNITY_PEDIA',		'TXT_KEY_POLICY_DIPLOMATIC_IMMUNITY_HELP',		'POLICY_BRANCH_PROSPERITY',     10,          2,     10,            'POLICY_ATLAS_EXP2', 'POLICY_A_ATLAS_EXP2'),
	('POLICY_TONNAGE_WAR',				'TXT_KEY_POLICY_TONNAGE_WAR',				'TXT_KEY_POLICY_TONNAGE_WAR_PEDIA',				'TXT_KEY_POLICY_TONNAGE_WAR_HELP',				'POLICY_BRANCH_PROSPERITY',     10,          2,     10,            'POLICY_ATLAS_EXP2', 'POLICY_A_ATLAS_EXP2'),
	('POLICY_PANOPTICISM',				'TXT_KEY_POLICY_PANOPTICISM',				'TXT_KEY_POLICY_PANOPTICISM_PEDIA',				'TXT_KEY_POLICY_PANOPTICISM_HELP',				'POLICY_BRANCH_PROSPERITY',     10,          2,     10,            'POLICY_ATLAS_EXP2', 'POLICY_A_ATLAS_EXP2'),
	('POLICY_INDIGO_ERA',				'TXT_KEY_POLICY_INDIGO_ERA',				'TXT_KEY_POLICY_INDIGO_ERA_PEDIA',				'TXT_KEY_POLICY_INDIGO_ERA_HELP',				'POLICY_BRANCH_PROSPERITY',     10,          2,     10,            'POLICY_ATLAS_EXP2', 'POLICY_A_ATLAS_EXP2'),
	('POLICY_CORPORATE_PERSONHOOD',		'TXT_KEY_POLICY_CORPORATE_PERSONHOOD',		'TXT_KEY_POLICY_CORPORATE_PERSONHOOD_PEDIA',	'TXT_KEY_POLICY_CORPORATE_PERSONHOOD_HELP',		'POLICY_BRANCH_PROSPERITY',     10,          2,     10,            'POLICY_ATLAS_EXP2', 'POLICY_A_ATLAS_EXP2'),
	('POLICY_COMPANY_TOWNS',			'TXT_KEY_POLICY_COMPANY_TOWNS',				'TXT_KEY_POLICY_COMPANY_TOWNS_PEDIA',			'TXT_KEY_POLICY_COMPANY_TOWNS_HELP',			'POLICY_BRANCH_PROSPERITY',     10,          2,     10,            'POLICY_ATLAS_EXP2', 'POLICY_A_ATLAS_EXP2'),
	('POLICY_BIG_PHARMA',				'TXT_KEY_POLICY_BIG_PHARMA',				'TXT_KEY_POLICY_BIG_PHARMA_PEDIA',				'TXT_KEY_POLICY_BIG_PHARMA_HELP',				'POLICY_BRANCH_PROSPERITY',     10,          2,     10,            'POLICY_ATLAS_EXP2', 'POLICY_A_ATLAS_EXP2'),
	('POLICY_CAMPAIGN_CONTRIBUTIONS',	'TXT_KEY_POLICY_CAMPAIGN_CONTRIBUTIONS',	'TXT_KEY_POLICY_CAMPAIGN_CONTRIBUTIONS_PEDIA',	'TXT_KEY_POLICY_CAMPAIGN_CONTRIBUTIONS_HELP',	'POLICY_BRANCH_PROSPERITY',		10,          3,     10,            'POLICY_ATLAS_EXP2', 'POLICY_A_ATLAS_EXP2'),
	('POLICY_HORIZONTAL_INTEGRATION',	'TXT_KEY_POLICY_HORIZONTAL_INTEGRATION',	'TXT_KEY_POLICY_HORIZONTAL_INTEGRATION_PEDIA',	'TXT_KEY_POLICY_HORIZONTAL_INTEGRATION_HELP',	'POLICY_BRANCH_PROSPERITY',		10,          3,     10,            'POLICY_ATLAS_EXP2', 'POLICY_A_ATLAS_EXP2'),
	('POLICY_PRIVATE_SPACEFLIGHT',		'TXT_KEY_POLICY_PRIVATE_SPACEFLIGHT',		'TXT_KEY_POLICY_PRIVATE_SPACEFLIGHT_PEDIA',		'TXT_KEY_POLICY_PRIVATE_SPACEFLIGHT_HELP',		'POLICY_BRANCH_PROSPERITY',		10,          3,     10,            'POLICY_ATLAS_EXP2', 'POLICY_A_ATLAS_EXP2');

--Temporary until text added
UPDATE Policies
SET Help = LOWER(SUBSTR(Type, 8))
WHERE PolicyBranchType = 'POLICY_BRANCH_PROSPERITY';

UPDATE Policies
SET Civilopedia = LOWER(SUBSTR(Type, 8))
WHERE PolicyBranchType = 'POLICY_BRANCH_PROSPERITY';